/*
    Hotel Room Booking System.
    
    Booking.java
    
    Joe O'Regan
    K00203642
    
    26/10/2017
    
    Booking takes a booking reference string, an integer array
    of days to be booked, and a room number integer value as 
    parameters.
    
    Printbooking() displays the details of a booking for a 
    number of days on a single room.
*/

import java.lang.reflect.Array;

public class Booking {
	String bookingRef;											// Unique booking reference (generated by the client)
	int[] days;													// Days to book
	int roomNum;												// The room number
	String displayBooking;										// Text to display when printing a Booking
	
	/*
	 * Override toString() to format the text
	 * when printing a Booking to screen
	 */
	@Override
    public String toString() {        
        return displayBooking;									// When you print out instance of Booking, value of its displayBooking field will be printed out
    }

	/* 
	 * Constructor:
	 * Takes booking reference, days, room number parameters
	 */
	public Booking (String br, int[] d, int r) {
		bookingRef = br;
		days = d;
		roomNum = r;	
		
		//displayBooking = "Booking Reference:\t" + 
		//bookingRef + "\nRoom Number:\t\t" + r + "\n";
		PrintBooking(br,d,r);									// moved to separate function, adding days
	}	

	/*
	 *  Display the booking details
	 */
	void PrintBooking(String br, int[] d, int r) {
		int i;
		displayBooking = "Booking Ref:\t" + br + "\nDays:\t\t";
		for(i = 0; i < Array.getLength(d) - 1; i++)
			displayBooking += d[i] + ", ";
		//displayBooking += d[i] + "\nRoom Number:\t" + r + "\n";
		displayBooking += d[i] + "\nRoom Number:\t" + r;
	}
}
