/*
    Hotel Room Booking System (Extended).
    
    Booking.java
    
    Joe O'Regan
    K00203642
    
    11/01/2018
    
    Extended:
    Booking class now has an array of days as a parameter
    PrintBooking() method now formats output for more than 1 room
*/

import java.lang.reflect.Array;

public class Booking {
	String bookingRef;											// Unique booking reference (generated by the client)
	int[] days;													// Days to book
	int[] roomNums;												// The room numbers
	String displayBooking;										// Text to display when printing a Booking

	/*
	 * Override toString() to format the text
	 * when printing a Booking to screen
	 */
	@Override
    public String toString() { 
        return displayBooking;									// When you print out instance of Booking, value of its displayBooking field will be printed out
    }
	
	/* 
	 * Constructor:
	 * Takes booking reference, days, room number parameters
	 */
	public Booking (String br, int[] d, int[] r) {
		bookingRef = br;										// Booking reference
		days = d;												// Array of days to book rooms for
		roomNums = r;											// Array of room numbers to book
		
		PrintBooking(br,d,r);									// moved to separate function, adding days
	}	

	/*
	 *  Display the booking details
	 */
	void PrintBooking(String br, int[] d, int[] r) {
		int i, j;
		displayBooking = "Booking Ref:\t" + br + "\nRoom(s):\t";
		for (i = 0; i < Array.getLength(r) - 1; i++)
			displayBooking += r[i] + ", ";
		displayBooking += r[i] + "\nDay(s)\t\t";
		for(j = 0; j < Array.getLength(d) - 1; j++)
			displayBooking += d[j] + ", ";
		displayBooking += d[j];
	}
}
