/*
    Hotel Room Booking System.
    
    Booking.java
    
    Joe O'Regan
    K00203642
    
    26/10/2017
*/

public class Booking {
	String bookingRef;	// Unique booking reference (generated by the client)
	int[] days;			// Days to book
	int roomNum;		// The room number
	
	public Booking (String br, int[] d, int r) {
		bookingRef = br;
		days = d;
		roomNum = r;
	}
}
