import java.lang.reflect.Array;

/*
    Hotel Room Booking System.
    
    Booking.java
    
    Joe O'Regan
    K00203642
    
    26/10/2017
*/

public class Booking {
	String bookingRef;								// Unique booking reference (generated by the client)
	int[] days;										// Days to book
	int roomNum;									// The room number
	String displayBooking;							// Text to display when printing a Booking
	
	// Override toString() to format the text when printing a Booking to screen
	@Override
    public String toString() {
        // When you print out instance of A, value of its foo field will be printed out
        return displayBooking;
    }
 	
	// booking reference, days, room number
	public Booking (String br, int[] d, int r) {
		bookingRef = br;
		days = d;
		roomNum = r;	
		
		//displayBooking = "Booking Reference:\t" + bookingRef + "\nRoom Number:\t\t" + r + "\n";
		PrintBooking(br,d,r);	// moved to separate function, adding days
	}	
	
	void PrintBooking(String br, int[] d, int r) {
		int i;
		displayBooking = "Booking Ref:\t" + br + "\nDays:\t\t";
		for(i = 0; i < Array.getLength(d) - 1; i++)
			displayBooking += d[i] + ", ";
		displayBooking += d[i] + "\nRoom Number:\t" + r + "\n";
	}
}
